# Generated by Django 3.2.20 on 2024-05-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address_details',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hno',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='street',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_experience',
        ),
    ]
