# Generated by Django 3.2.20 on 2024-05-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0003_auto_20240511_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_employee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
