# Generated by Django 3.2.20 on 2024-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0004_alter_reg_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
